#!/usr/bin/env python3
import ROOT
import glob
import os
import sys
import argparse
import re
import uproot
import numpy as np

from utils import load_and_select_events, analyze_event, check_event_tree

branch_pairs = {
    ("theta", "theta_m2"): {"range": (0, 90), "xlabel": "#theta"},
    ("phi", "phi_m2"): {"range": (-180, 180), "xlabel": "#phi"},
}

def compare_distributions(
    input_file, output_dir, multiplicity_config=None, base_name="params_compare", nbins=60
    
):
    """Compare theta/theta_m2 and phi/phi_m2 for events matching given multiplicities.

    Parameters:
      - input_file: ROOT file containing events and track trees.
      - output_dir: output directory
      - multiplicity_config: multiplicity requirements used for the selection inside this function
    """

    x0_sel, x0_m2_sel, mask1, mask2, tree1, tree2 = check_event_tree(
        input_file, output_dir, multiplicity_config
    )

    norm_hist = False # set to True to normalize histograms to unit area

    print(f"\n🔍 --- Comparing angular distributions (x0_mult = {x0_sel}, x0_m2_mult = {x0_m2_sel}) ---") 

    ROOT.gStyle.SetOptStat(0)
    ROOT.gROOT.SetBatch(True)

    c = ROOT.TCanvas("c_compare", "Angular comparison", 900, 700)

    out_root = os.path.join(output_dir, f"{base_name}_x0_{x0_sel}_x0m2_{x0_m2_sel}.root")
    fout = ROOT.TFile(out_root, "RECREATE")

    pdf_path = os.path.join(output_dir, f"{base_name}_x0_{x0_sel}_x0m2_{x0_m2_sel}.pdf")
    c.Print(pdf_path + "[") 

    # loop over branches pairs
    for (b1, b2), cgf in branch_pairs.items():
        xmin, xmax = cgf["range"]
        xlabel = cgf.get("xlabel", b1)

        h1 = ROOT.TH1F(f"h_{b1}_cmp", f"{xlabel}_hist;{xlabel} (#circ);Entries", int(nbins), float(xmin), float(xmax))
        h2 = ROOT.TH1F(f"h_{b2}_cmp", f"{xlabel}_hist;{xlabel} (#circ);Entries", int(nbins), float(xmin), float(xmax))

        # Read branches
        arr1 = tree1[b1].array(library="np")
        arr2 = tree2[b2].array(library="np")

        # fill with masks
        for v in arr1[mask1]:
            h1.Fill(float(v))

        for v in arr2[mask2]:
            h2.Fill(float(v))

        if norm_hist:
            h1.Scale(1.0 / h1.Integral(), "width")
            h2.Scale(1.0 / h2.Integral(), "width")

        h1.SetLineColor(ROOT.kBlue)
        h2.SetLineColor(ROOT.kRed)
        h1.SetLineWidth(2)
        h2.SetLineWidth(2)

        ymax = max(h1.GetMaximum(), h2.GetMaximum()) * 1.2
        h1.SetMaximum(ymax)
        h2.SetMaximum(ymax)

        # Draw
        h1.Draw("HIST")
        h2.Draw("HIST SAME")

        leg = ROOT.TLegend(0.62, 0.78, 0.90, 0.90)
        leg.AddEntry(h1, xlabel + f" - Entries: {int(h1.GetEntries())}", "l")
        leg.AddEntry(h2, xlabel + f"_m2 - Entries: {int(h2.GetEntries())}", "l")
        #leg.AddEntry(h1, f"Entries: {h1.GetEntries()}", "")
        #leg.AddEntry(h2, f"Entries: {h2.GetEntries()}", "")
        leg.SetTextSize(0.038)
        leg.Draw()

        c.Print(pdf_path)

        fout.cd()
        h1.Write()
        h2.Write()

    c.Print(pdf_path + "]")
    fout.Close()

    print(f"\n✅ Saved comparison plots to {pdf_path}")
    print(f"✅ Saved histograms to {out_root}")


if __name__ == "__main__":    
    parser = argparse.ArgumentParser(
        description="Compare track multiplicity histograms across ROOT files. To be executed after check_extra_tracks.py with all the cuts applied."
    )
    parser.add_argument(
        "--input",
        "-i",
        required=True,
        help="Input root file with distributions to compare. Root file generated by check_extra_tracks.py.",
    )
    parser.add_argument(
        "--output",
        "-o",
        required=True,
        help="Output directory where results will be stored",
    )

    args = parser.parse_args()

    input_file = os.path.abspath(args.input)
    output_dir = os.path.abspath(args.output)

    multiplicity_config = {
        "x0_count": None, 
        "x0_m2_count": None
    }
    
    compare_distributions(input_file, output_dir, multiplicity_config)